version: '3'
services:
  bot:
    build: .
    environment:
      - EVERYDAY_KATARIBE_TOKEN
      - TWITTER_BEARER_TOKEN
      - RANDOM_POST_TWEET_SCHEDULE
      - ACTIVITY_STREAMING_NAME
      - ACTIVITY_STREAMING_URL
