name: Build and deploy Docker Image

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

  workflow_dispatch:

jobs:
  generate_image_name:
    runs-on: ubuntu-latest

    outputs:
      docker_image_name: ${{ steps.generate_docker_image_name.outputs.result }}

    steps:
      - name: Generate Docker image name
        id: generate_docker_image_name
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: return `ghcr.io/${'${{ github.repository }}'.toLowerCase()}`;

  generate_image_tags:
    needs: generate_image_name

    runs-on: ubuntu-latest

    outputs:
      docker_image_tags: ${{ steps.generate_docker_image_tags.outputs.result }}

    steps:
      - name: Generate Docker images tags
        id: generate_docker_image_tags
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const imageName = '${{ needs.generate_image_name.outputs.docker_image_name }}';
            const shortSHA = '${{ github.sha }}'.slice(0, 7);
            let imageTags = `${imageName}:latest\n${imageName}:${shortSHA}`;
            if ('${{ github.event_name }}' === 'tags') {
              const gitTag = '${{ github.ref }}'.replace(/refs\/tags\/v?/, '');
              imageTags += `\n${imageName}:${gitTag}`;
            }
            return imageTags;

  build:
    needs: generate_image_tags

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install npm packages
        run: npm ci

      - name: Compile TypeScript
        run: tsc

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: .
          push: true
          tags: ${{ needs.generate_image_tags.outputs.docker_image_tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move Docker image chace
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Set IMAGE_NAME
  #       run: echo IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr A-Z a-z) >> $GITHUB_ENV

  #     - name: Deploy docker image to remote
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_KEY }}
  #         port: ${{ secrets.SSH_PORT }}
  #         script: |
  #           cd ${{ secrets.PRODUCTION_PATH }}
